### ISSUE TITLE
OnIconSelectedCallback

### ISSUE THREAD

**Issue by jrcacd** [maltaisn/icondialoglib#14]
Can be done?

```
IconDialog()
.OnIconSelected{

}
.show(activity!!.supportFragmentManager, "icon_dialog")
```

It is much more intuitive and easy to have these even on fragments than override the **onIconDialogIconsSelected** on the activity and send the selected icon to the coresponded fragment

```
override fun onIconDialogIconsSelected(icons: Array<out Icon>) {

}
```

**Comment by maltaisn** [comment]
Make the fragment implement the interface and call `show()` with the fragment's `getChildFragmentManager()`. The dialog will automatically callback to the fragment. The solution you proposed doesn't work since the listener would need to be saved on configuration change, which is not possible. (and would lead to a memory leak anyway)
