### ISSUE TITLE
Getting a particular icon synchronously based on ID

### ISSUE THREAD

**Issue by dirkam** [maltaisn/icondialoglib#18]
Is it possible to get a particular icon drawable based on the ID? Tried IconView and IconHelper but they seem to be loading all icons asynchronously, is it necessary even if we only need one particular icon?

**Comment by maltaisn** [comment]
You can use `IconHelper.getInstance(Context).getIcon(id)`. 

The icon helper data like icons and labels is loaded asynchronously because it takes some time. You can have a loop at the start of your app that just wait until the icon helper is loaded, and then you can get any icon. You can also use the icon helper load callback. If you need more help on this I can provide some code samples.

**Comment by dirkam** [comment]
Sure, it works. My question was if getting a particular icon synchronously based on ID is possible? Is there any way to do it? If not, would it be possible for you to add such an option?

**Comment by maltaisn** [comment]
You can get icons synchronously once the data is loaded. You could probably do:
```java
IconHelper helper = IconHelper.getInstance(context)
while (!helper.isDataLoaded()) {
    // Wait. You could add a 30ms sleep here it would be better.
}
Icon icon = helper.getIcon(id)
```
Although it isn't the best solution since loading can take something like 0.2 s - 2 s. Your app might just freeze for a moment. I highly recommend using the callback, or calling the above block of code in another thread on startup.

**Comment by AyusmaTech** [comment]
@maltaisn Hello, I am trying to get an icon with an ID also. But the IconHelper class was replaced with IconPackLoader, and I have been trying to solve this, but I didn't find a solution. Could you please show me how I can do that?

**Comment by maltaisn** [comment]
Ideally it should not be done synchronously, except maybe on app startup as shown in the wiki example. But if you still decide to do it synchronously, then the usage is the same:
###### Java
```java
IconPackLoader loader = new IconPackLoader(context);
IconPack iconPack = IconPackDefault.createDefaultIconPack(loader);
Drawable iconDrawable = iconPack.getIconDrawable(<id>, loader.getDrawableLoader());
```
###### Kotlin
```kotlin
val loader = IconPackLoader(context)
val iconPack = createDefaultIconPack(loader)
val iconDrawable = iconPack.getIconDrawable(<id>, loader.drawableLoader)
```
It's been a while since I've used my own library, but I think that should work. There's also a `IconPack.loadDrawables(IconDrawableLoader)` method to preload all drawables in a pack, but it's probably best you don't do this synchronously. That's the part that can take a few seconds.
