### ISSUE TITLE
Single picker

### ISSUE THREAD

**Issue by OscarCaro** [maltaisn/icondialoglib#25]
This icon picker allows the user to choose several icons at the same time.
Is there a way to adapt it so that only one icon can be selected?
TIA. Love your project!

**Comment by maltaisn** [comment]
Single selection is the default behavior. Please take a look at the [IconDialogSettings](https://github.com/maltaisn/icondialoglib/blob/master/lib/src/main/kotlin/com/maltaisn/icondialog/IconDialogSettings.kt) docs. There's a `maxSelection` option which is set to 1 by default. You can also hide the select button so that a click on an icon will immediately select it and close the dialog.

**Comment by OscarCaro** [comment]
Glad to hear that. I got the wrong idea from the video on the README. Thank you so much. I will use it on my app.
