### ISSUE TITLE
Using custom icon packs

### ISSUE THREAD

**Issue by OscarCaro** [maltaisn/icondialoglib#28]
I'm having some trouble using my own icon pack, specifically with this line of kotlin code (from the documentation):
`val iconPack = loader.load(R.xml.icons, R.xml.tags, listOf(Locale.ENGLISH))`
Since I'm not confident enough with Kotlin, I decided to implement that class in Java, but I can't figure out the equivalent in Java for listOf. I've tried with arrayList and many other lists, but they are not accepted.
I know that, at last, I could implement the whole class in kotlin, but I wouldn't like to.
Thank you so so much, since this is more of a kotlin doubt than an issue in your project.

**Comment by maltaisn** [comment]
Most if not all of Java lists should be accepted. The problem here is that you're missing the `parentPack` argument, which is used to extend an existing pack. You can use `null` otherwise:
```
IconPack iconPack = loader.load(R.xml.icons, R.xml.tags, Collections.singletonList(Locale.ENGLISH), null);
```
You can use `Arrays.asList(...)` if you support more languages. 

The Kotlin `IconPackLoader.load` methods has some default parameter values, which is why you can omit the last argument. These are not available from Java so you have to specify them all.
