### ISSUE TITLE
Selected Icon Background

### ISSUE THREAD

**Issue by jhansen2015** [maltaisn/icondialoglib#37]
Problem description: The currently selected icon color is styleable, but the background for the currently selected icon cannot be changed.

Solution / Feature request: Add a style/configuration setting for `selectedIconBackground`.

**Comment by jhansen2015** [comment]
BTW, thank you for the excellent library!

**Comment by maltaisn** [comment]
Here's what I changed in v3.3.0. 

I made the ImageView used to display icons checkable, meaning it now recognizes the `android:state_checked` state attribute. You can use color state lists (`<selector>`) to specify different styles for normal and selected states, for any color or drawable attribute, including `tint` and `android:background`.

As such, `icdIconColor` and `icdSelectedIconColor` aren't even be needed anymore, because the same can be achieved with a custom `icdIconStyle` and the `tint` attribute. (although they were kept for backward compatibility) 

For a custom background, you can now do something like this:

###### values/styles.xml
```xml
<style name="CustomIconDialogStyle" parent="IcdStyle">
    <item name="icdIconStyle">@style/CustomIconStyle</item>
</style>

<style name="CustomIconStyle" parent="IcdIconStyle">
    <item name="android:background">@drawable/custom_icon_background</item>
</style>
```
###### drawable/custom_icon_background.xml
```xml
<selector xmlns:android="http://schemas.android.com/apk/res/android">
    <item android:state_checked="true">
        <shape>
            <corners android:radius="8dp"/>
            <stroke android:width="3dp" android:color="?icdSelectedIconColor"/>
        </shape>
    </item>
    <item>
        <color android:color="@android:color/transparent"/>
    </item>
</selector>
```
The result:
<img src="https://user-images.githubusercontent.com/33690959/82851332-782e3580-9ecd-11ea-8405-f78219261428.png" width="75%"/>

Note that this particular example only works for API 21 and above.

I hope that's what you needed. Also don't forget to read the [release notes](https://github.com/maltaisn/icondialoglib/blob/master/CHANGELOG.md), there are a few things I haven't mentioned.

**Comment by jhansen2015** [comment]
Thank you! Very nice implementation! It works really well. It works on API 16+ by using a non-attribute color reference, and in your example, setting the checked shape to have a solid color of `transparent` (otherwise it shows black inside the rounded outline). This works fine for my current use case because I don't have different themes yet, and therefore, no need for different colors.

```
<selector xmlns:android="http://schemas.android.com/apk/res/android">
    <item android:state_checked="true">
        <shape>
            <solid android:color="@android:color/transparent"/>
            <corners android:radius="8dp"/>
            <stroke android:width="3dp" android:color="@android:color/holo_blue_dark"/>
        </shape>
    </item>
    <item>
        <color android:color="@android:color/transparent"/>
    </item>
</selector>
```

Maybe Google will fix the bug soon!

Thanks again!
