### ISSUE TITLE
Crashing on API 21

### ISSUE THREAD

**Issue by amorangi** [maltaisn/icondialoglib#5]
When I run 1.1.0 or 1.1.1 on a Nexus 5 API 21 I get the following crash:

08-08 06:12:22.933 1900-1900/com.maltaisn.icondialoglib E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.maltaisn.icondialoglib, PID: 1900
    android.view.InflateException: Binary XML file line #23: Error inflating class <unknown>

Seems ok with later APIs though. However in the instructions it recommends min API of 21.

**Comment by maltaisn** [comment]
This is entirely possible, I didn't test it on API 21, I just assumed it would work. This is probably due to how the vector binary XML file is created programmatically. I'll look into it soon.

**Comment by maltaisn** [comment]
Unfortunately, it looks like my processor can't run the emulator and I can't test it right now, it may take a while. In the meantime, can you check if this is a device specific issue? (or were you using the emulator?)

**Comment by amorangi** [comment]
I was running on an emulator. I've checked it crashes on API 22 as well, but seems fine on API 23 (ASOP 6.0) and up. I've run it on 2 different emulator types as well, so it's not emulator specific either.
Have you tried Genymotion for emulation (assuming your issue is AMD processor)?

**Comment by maltaisn** [comment]
I managed to get the emulator working. The crash happens when the dialog layout is inflated, there's an error inflating `ConstraintLayout` and every other views, the inflater can't instantiate any class through reflection. I tried using both the layout inflater from `getActivity().getLayoutInflater()` and `LayoutInflater.from(Context)` without success. I have honestly no idea how to fix this.

**Comment by maltaisn** [comment]
Fixed it by changing `?android:attr/colorBackgroundFloating` (probably available from API 23) to its AppCompat equivalent, `?attr/colorBackgroundFloating`.
